services:
  jekyll:
    image: jekyll/jekyll:4
    command: |
      bash -c "
        bundle check || bundle install &&
        bundle exec jekyll serve --watch --host 0.0.0.0
      "
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
